[pytest]
markers=
        sanity: Marks test as sanity
        regression: No description
        smoke:
        math:
        web:
        user_profile:
        dependency:

#all these are user defined markers
